import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

//
import { FooterBanner, HeroBanner } from "../components";

const Home: NextPage = () => {
  return (
    <div className="">
      <Head>
        <title>Minimal Ecommerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeroBanner />

      <div className="text-center text-[#324d67] mx-10 my-0">
        <h2 className="text-[40px] font-extrabold">Best selling products</h2>
        <p className="text-base font-extralight">Speaker of many variations</p>
      </div>
      <div className="flex flex-wrap gap-[15px] w-full justify-center mt-5">
        {["procudt 1", "product 2"].map((product) => product)}
      </div>
      <FooterBanner />
    </div>
  );
};

export default Home;
